In [1]:
!pip install yfinance

Collecting yfinance
  Obtaining dependency information for yfinance from https://files.pythonhosted.org/packages/8e/fc/2d99838a91407dffa6c9e99a2119ba593ed43f122c638e7aa5d342816a32/yfinance-0.2.26-py2.py3-none-any.whl.metadata
  Downloading yfinance-0.2.26-py2.py3-none-any.whl.metadata (11 kB)
Collecting pandas>=1.3.0 (from yfinance)
  Obtaining dependency information for pandas>=1.3.0 from https://files.pythonhosted.org/packages/3c/b2/0d4a5729ce1ce11630c4fc5d5522a33b967b3ca146c210f58efde7c40e99/pandas-2.0.3-cp310-cp310-macosx_10_9_x86_64.whl.metadata
  Downloading pandas-2.0.3-cp310-cp310-macosx_10_9_x86_64.whl.metadata (18 kB)
Collecting numpy>=1.16.5 (from yfinance)
  Obtaining dependency information for numpy>=1.16.5 from https://files.pythonhosted.org/packages/fa/07/c6980120967a9fc76138eddd583d6ac47dd072922d6f66d7d502f6f9a964/numpy-1.25.1-cp310-cp310-macosx_10_9_x86_64.whl.metadata
  Downloading numpy-1.25.1-cp310-cp310-macosx_10_9_x86_64.whl.metadata (5.6 kB)
Collecting requests>=2.31 (from yfinance)
  Obtaining dependency information for requests>=2.31 from https://files.pythonhosted.org/packages/70/8e/0e2d847013cb52cd35b38c009bb167a1a26b2ce6cd6965bf26b47bc0bf44/requests-2.31.0-py3-none-any.whl.metadata
  Downloading requests-2.31.0-py3-none-any.whl.metadata (4.6 kB)
Collecting multitasking>=0.0.7 (from yfinance)
  Using cached multitasking-0.0.11-py3-none-any.whl (8.5 kB)
Requirement already satisfied: lxml>=4.9.1 in /Users/miryam.chen/opt/anaconda3/envs/UdacityCapstone/lib/python3.10/site-packages (from yfinance) (4.9.2)
Collecting appdirs>=1.4.4 (from yfinance)
  Downloading appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Collecting pytz>=2022.5 (from yfinance)
  Using cached pytz-2023.3-py2.py3-none-any.whl (502 kB)
Collecting frozendict>=2.3.4 (from yfinance)
  Downloading frozendict-2.3.8-cp310-cp310-macosx_10_9_x86_64.whl (36 kB)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /Users/miryam.chen/opt/anaconda3/envs/UdacityCapstone/lib/python3.10/site-packages (from yfinance) (4.12.2)
Collecting html5lib>=1.1 (from yfinance)
  Using cached html5lib-1.1-py2.py3-none-any.whl (112 kB)
Requirement already satisfied: soupsieve>1.2 in /Users/miryam.chen/opt/anaconda3/envs/UdacityCapstone/lib/python3.10/site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.4)
Requirement already satisfied: six>=1.9 in /Users/miryam.chen/opt/anaconda3/envs/UdacityCapstone/lib/python3.10/site-packages (from html5lib>=1.1->yfinance) (1.16.0)
Requirement already satisfied: webencodings in /Users/miryam.chen/opt/anaconda3/envs/UdacityCapstone/lib/python3.10/site-packages (from html5lib>=1.1->yfinance) (0.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/miryam.chen/opt/anaconda3/envs/UdacityCapstone/lib/python3.10/site-packages (from pandas>=1.3.0->yfinance) (2.8.2)
Collecting tzdata>=2022.1 (from pandas>=1.3.0->yfinance)
  Using cached tzdata-2023.3-py2.py3-none-any.whl (341 kB)
Collecting charset-normalizer<4,>=2 (from requests>=2.31->yfinance)
  Obtaining dependency information for charset-normalizer<4,>=2 from https://files.pythonhosted.org/packages/81/a0/96317ce912b512b7998434eae5e24b28bcc5f1680ad85348e31e1ca56332/charset_normalizer-3.2.0-cp310-cp310-macosx_10_9_x86_64.whl.metadata
  Downloading charset_normalizer-3.2.0-cp310-cp310-macosx_10_9_x86_64.whl.metadata (31 kB)
Requirement already satisfied: idna<4,>=2.5 in /Users/miryam.chen/opt/anaconda3/envs/UdacityCapstone/lib/python3.10/site-packages (from requests>=2.31->yfinance) (3.4)
Collecting urllib3<3,>=1.21.1 (from requests>=2.31->yfinance)
  Obtaining dependency information for urllib3<3,>=1.21.1 from https://files.pythonhosted.org/packages/9b/81/62fd61001fa4b9d0df6e31d47ff49cfa9de4af03adecf339c7bc30656b37/urllib3-2.0.4-py3-none-any.whl.metadata
  Downloading urllib3-2.0.4-py3-none-any.whl.metadata (6.6 kB)
Collecting certifi>=2017.4.17 (from requests>=2.31->yfinance)
  Obtaining dependency information for certifi>=2017.4.17 from https://files.pythonhosted.org/packages/4c/dd/2234eab22353ffc7d94e8d13177aaa050113286e93e7b40eae01fbf7c3d9/certifi-2023.7.22-py3-none-any.whl.metadata
  Downloading certifi-2023.7.22-py3-none-any.whl.metadata (2.2 kB)
Using cached yfinance-0.2.26-py2.py3-none-any.whl (62 kB)
Downloading numpy-1.25.1-cp310-cp310-macosx_10_9_x86_64.whl (20.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.1/20.1 MB 35.2 MB/s eta 0:00:0000:0100:01
Downloading pandas-2.0.3-cp310-cp310-macosx_10_9_x86_64.whl (11.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.8/11.8 MB 33.6 MB/s eta 0:00:0000:0100:01
Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Downloading certifi-2023.7.22-py3-none-any.whl (158 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 158.3/158.3 kB 14.7 MB/s eta 0:00:00
Downloading charset_normalizer-3.2.0-cp310-cp310-macosx_10_9_x86_64.whl (126 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 126.4/126.4 kB 11.8 MB/s eta 0:00:00
Downloading urllib3-2.0.4-py3-none-any.whl (123 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 123.9/123.9 kB 12.0 MB/s eta 0:00:00
Installing collected packages: pytz, multitasking, appdirs, urllib3, tzdata, numpy, html5lib, frozendict, charset-normalizer, certifi, requests, pandas, yfinance
Successfully installed appdirs-1.4.4 certifi-2023.7.22 charset-normalizer-3.2.0 frozendict-2.3.8 html5lib-1.1 multitasking-0.0.11 numpy-1.25.1 pandas-2.0.3 pytz-2023.3 requests-2.31.0 tzdata-2023.3 urllib3-2.0.4 yfinance-0.2.26

In [2]:
import yfinance as yf

In [5]:
#list of symbols I am interested in
symbols = ['BRK-B', 'BERY', 'BN', 'GOOGL', 'CCL', 'DG', 'DAVA', 'PYPL']

In [6]:
#create empty list to store data for each symbol
data = {}

In [7]:
#loop through each symbol and get data
for symbol in symbols:
    df=yf.download(symbol, start='2015-01-01', end='2023-06-30')
    #store the data in the dictionary
    data[symbol]=df

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

In [9]:
for symbol, df in data.items():

                 Open       High        Low      Close  Adj Close   Volume
Date
2015-07-06  38.000000  39.750000  36.000000  36.709999  36.709999  5866600
2015-07-07  37.720001  37.810001  36.000000  36.619999  36.619999  7359000
2015-07-08  36.340000  36.360001  34.529999  34.700001  34.700001  5387700
2015-07-09  35.099998  35.520000  33.990002  34.500000  34.500000  3760100
2015-07-10  34.660000  35.189999  33.980000  34.689999  34.689999  4472800

In [11]:
for symbol, df in data.items():
    print(f"data for [BN]:")
    print(df)
    print()

data for [BN]:
                  Open        High         Low       Close   Adj Close  \
Date
2015-01-02  151.500000  151.600006  148.500000  149.169998  149.169998
2015-01-05  148.809998  149.000000  146.779999  147.000000  147.000000
2015-01-06  147.639999  148.529999  146.110001  146.839996  146.839996
2015-01-07  147.940002  149.139999  147.649994  148.880005  148.880005
2015-01-08  150.600006  151.369995  150.509995  151.369995  151.369995
...                ...         ...         ...         ...         ...
2023-06-23  335.100006  337.470001  334.190002  335.250000  335.250000
2023-06-26  335.170013  335.829987  331.839996  334.119995  334.119995
2023-06-27  334.390015  336.730011  334.369995  335.339996  335.339996
2023-06-28  336.049988  336.399994  332.609985  334.149994  334.149994
2023-06-29  334.260010  337.010010  334.140015  336.910004  336.910004

             Volume
Date
2015-01-02  3436400
2015-01-05  4168800
2015-01-06  4116100
2015-01-07  4159100
2015-01-08  4282100
...             ...
2023-06-23  4451700
2023-06-26  3220900
2023-06-27  2625600
2023-06-28  3175100
2023-06-29  2498900

[2137 rows x 6 columns]

data for [BN]:
                 Open       High        Low      Close  Adj Close   Volume
Date
2015-01-02  31.580000  31.760000  31.340000  31.740000  31.338293  1216200
2015-01-05  31.559999  31.889999  31.360001  31.700001  31.298801  1378600
2015-01-06  31.850000  32.230000  31.309999  31.820000  31.417282  1773600
2015-01-07  32.029999  32.029999  31.639999  31.950001  31.545639  1286700
2015-01-08  32.349998  32.580002  31.990000  32.189999  31.782600  1646400
...               ...        ...        ...        ...        ...      ...
2023-06-23  62.330002  62.610001  61.470001  62.220001  62.220001  2059500
2023-06-26  61.950001  63.189999  61.650002  62.720001  62.720001   792700
2023-06-27  62.779999  64.330002  62.000000  64.220001  64.220001   838800
2023-06-28  64.139999  64.139999  63.209999  63.639999  63.639999   826200
2023-06-29  63.360001  64.220001  63.040001  63.889999  63.889999  1030500

[2137 rows x 6 columns]

data for [BN]:
                 Open       High        Low      Close  Adj Close   Volume
Date
2015-01-02  17.695848  17.812548  17.490740  17.794865  15.799126  1025071
2015-01-05  17.692312  17.713530  17.557932  17.614511  15.639004  1553018
2015-01-06  17.586222  17.667557  17.388186  17.427086  15.472595  1649162
2015-01-07  17.557932  17.812548  17.420013  17.734749  15.745753  1611836
2015-01-08  17.879738  18.240444  17.840837  18.229836  16.185320  1514843
...               ...        ...        ...        ...        ...      ...
2023-06-23  31.360001  31.549999  30.940001  31.330000  31.330000  1686500
2023-06-26  31.330000  31.639999  31.129999  31.480000  31.480000  2113800
2023-06-27  31.469999  32.349998  31.420000  32.240002  32.240002  3205600
2023-06-28  32.220001  32.450001  31.930000  32.410000  32.410000  1766200
2023-06-29  32.439999  32.669998  32.130001  32.599998  32.599998  1670100

[2137 rows x 6 columns]

data for [BN]:
                  Open        High         Low       Close   Adj Close  \
Date
2015-01-02   26.629999   26.790001   26.393999   26.477501   26.477501
2015-01-05   26.357500   26.399500   25.887501   25.973000   25.973000
2015-01-06   26.025000   26.060499   25.277500   25.332001   25.332001
2015-01-07   25.547501   25.574499   25.182501   25.257500   25.257500
2015-01-08   25.075500   25.375000   24.750999   25.345501   25.345501
...                ...         ...         ...         ...         ...
2023-06-23  121.379997  122.790001  121.059998  122.339996  122.339996
2023-06-26  120.760002  122.000000  118.269997  118.339996  118.339996
2023-06-27  117.080002  119.080002  116.099998  118.330002  118.330002
2023-06-28  117.089996  120.389999  116.849998  120.180000  120.180000
2023-06-29  119.239998  120.059998  118.300003  119.099998  119.099998

              Volume
Date
2015-01-02  26480000
2015-01-05  41182000
2015-01-06  54456000
2015-01-07  46918000
2015-01-08  73054000
...              ...
2023-06-23  34885300
2023-06-26  33969900
2023-06-27  39535900
2023-06-28  27091400
2023-06-29  24090900

[2137 rows x 6 columns]

data for [BN]:
                 Open       High        Low      Close  Adj Close     Volume
Date
2015-01-02  45.910000  46.110001  45.310001  45.610001  38.915909    2769700
2015-01-05  46.180000  46.200001  45.299999  45.389999  38.728199    4301500
2015-01-06  45.630001  46.169998  45.020000  45.830002  39.103622    6216100
2015-01-07  45.889999  46.290001  45.740002  46.000000  39.248669    7102600
2015-01-08  46.070000  46.970001  46.029999  46.680000  39.828869    4910000
...               ...        ...        ...        ...        ...        ...
2023-06-23  15.490000  16.000000  15.430000  15.800000  15.800000   39357500
2023-06-26  14.980000  15.040000  13.900000  14.600000  14.600000  107033000
2023-06-27  14.750000  15.910000  14.700000  15.890000  15.890000   62431700
2023-06-28  15.940000  17.490000  15.880000  17.290001  17.290001   96977000
2023-06-29  17.250000  17.750000  16.879999  17.160000  17.160000   60301600

[2137 rows x 6 columns]

data for [BN]:
                  Open        High         Low       Close   Adj Close  \
Date
2015-01-02   70.699997   71.470001   70.599998   70.779999   64.749710
2015-01-05   70.500000   71.070000   70.010002   70.320000   64.328873
2015-01-06   70.480003   70.910004   69.150002   69.430000   63.514721
2015-01-07   70.019997   70.610001   69.599998   70.269997   64.283165
2015-01-08   70.000000   70.419998   68.760002   69.510002   63.587891
...                ...         ...         ...         ...         ...
2023-06-23  172.000000  173.089996  170.029999  171.149994  170.553650
2023-06-26  171.389999  171.919998  167.559998  167.690002  167.105713
2023-06-27  167.309998  169.639999  166.039993  169.399994  168.809753
2023-06-28  169.110001  169.770004  166.330002  167.050003  166.467957
2023-06-29  165.960007  168.000000  165.410004  166.770004  166.188919

             Volume
Date
2015-01-02  2717000
2015-01-05  2508500
2015-01-06  3640300
2015-01-07  4239000
2015-01-08  8738500
...             ...
2023-06-23  7117000
2023-06-26  2708900
2023-06-27  2722000
2023-06-28  2323000
2023-06-29  1936800

[2137 rows x 6 columns]

data for [BN]:
                 Open       High        Low      Close  Adj Close   Volume
Date
2018-07-27  25.000000  26.000000  24.129999  25.200001  25.200001  4774000
2018-07-30  24.799999  25.250000  23.000000  23.250000  23.250000   885800
2018-07-31  23.250000  24.469999  23.250000  23.910000  23.910000   292500
2018-08-01  23.809999  24.100000  23.299999  23.799999  23.799999   201900
2018-08-02  23.709999  26.410000  23.290001  24.799999  24.799999   282800
...               ...        ...        ...        ...        ...      ...
2023-06-23  49.130001  49.419998  47.770000  48.189999  48.189999   359000
2023-06-26  48.080002  48.950001  47.750000  47.990002  47.990002   195200
2023-06-27  47.990002  49.740002  47.250000  49.240002  49.240002   202500
2023-06-28  48.889999  49.980000  48.759998  49.490002  49.490002   204200
2023-06-29  49.580002  50.570000  49.130001  50.290001  50.290001   127900

[1239 rows x 6 columns]

data for [BN]:
                 Open       High        Low      Close  Adj Close    Volume
Date
2015-07-06  38.000000  39.750000  36.000000  36.709999  36.709999   5866600
2015-07-07  37.720001  37.810001  36.000000  36.619999  36.619999   7359000
2015-07-08  36.340000  36.360001  34.529999  34.700001  34.700001   5387700
2015-07-09  35.099998  35.520000  33.990002  34.500000  34.500000   3760100
2015-07-10  34.660000  35.189999  33.980000  34.689999  34.689999   4472800
...               ...        ...        ...        ...        ...       ...
2023-06-23  67.415001  68.160004  65.849998  66.940002  66.940002  27616200
2023-06-26  66.870003  67.580002  66.410004  66.440002  66.440002  12224400
2023-06-27  66.870003  67.099998  65.779999  66.230003  66.230003  16371200
2023-06-28  66.050003  66.480003  65.620003  66.029999  66.029999  15390600
2023-06-29  66.300003  67.339996  65.620003  65.860001  65.860001  14894200

[2011 rows x 6 columns]